mybatis:
  mapper-locations: classpath:com.example.demo.dao/*.xml
  type-aliases-package: com.example.demo.dao

# 数据库配置
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver