mybatis:
  mapper-locations: classpath:com.example.demo.dao/*.xml
  type-aliases-package: com.example.demo.dao

# 数据库配置(mysql 8.0)
spring:
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver

  # 数据库配置(mysql 5.0)
  datasource:
    username: mytijian
    password: mytijian
    url: jdbc:mysql://192.168.5.5:3306/117
    driver-class-name: com.mysql.cj.jdbc.Driver